application:
  title: Servicio para Gestiòn Cliente
  version: 1.0.0
  author: Michael Ponce


server:
  port: 9001

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRESQL.URL.CONNECTION:jdbc:postgresql://localhost:5432/bancodb}
    username: postgres
    password: asinfo2680$
    driver-class-name: org.postgresql.Driver
  
